version: "3.9"
services:

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: "rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      options:
        max-size: "10m"
        max-file: "10"

#docker run -p 1080:1080 -p 1025:1025 maildev/maildev
  maildev:
    image: maildev/maildev
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  postgres:
    image: postgres:13.3
    container_name: "postgres"
    volumes:
      - ./postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"

  server:
    image: backend-server
    container_name: backend-server
    build: ./server
    volumes:
      - ../src:/opt/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  mail_service:
    image: mail-service
    container_name: mail-service
    build: ./mail-service
    volumes:
      - ../src:/opt/app
    ports:
      - "8081:8081"
    depends_on:
        - maildev
        - rabbitmq

#  client:
#    image: vue-client
#    container_name: vue-client
#    build: ./client
#    ports:
#      - "8081:8081"

